---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-controller-operator.fullname" . }}-metrics-service-source
  labels:
    {{- include "helm-controller-operator.labels" . | nindent 4 }}
spec:
  ports:
    {{- if .Values.kubeRBACProxy.enabled }}
    - name: https-metrics
      port: 8443
      targetPort: https-metrics
      protocol: TCP
    {{- else }}
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "helm-controller-operator.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-controller-operator.fullname" . }}-source
  labels:
    {{- include "helm-controller-operator.labels" . | nindent 4 }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    {{- include "helm-controller-operator.selectorLabels" . | nindent 4 }}
