---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helm-controller-stack.sourceControllerFullname" . }}
  labels:
    {{- include "helm-controller-stack.sourceControllerLabels" . | nindent 4 }}
spec:
  replicas: {{ .Values.sourceController.manager.replicaCount }}
  selector:
    matchLabels:
      {{- include "helm-controller-stack.sourceControllerSelectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- range $key, $value := .Values.sourceController.manager.podAnnotations }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
      labels:
        {{- include "helm-controller-stack.sourceControllerLabels" . | nindent 8 }}
    spec:
      containers:
      - args:
        - --watch-all-namespaces
        - --enable-leader-election
        - --storage-path=/data
        - --storage-adv-addr=source-controller.$(RUNTIME_NAMESPACE).svc.cluster.local.
        {{- range $key, $value := .Values.sourceControllerLabels.manager.extraArgs }}
        - "-{{ $key }}={{ $value }}"
        {{- end }}
        env:
        - name: RUNTIME_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        {{- with .Values.sourceController.manager.image }}
        image: "{{ .repository }}:{{ .tag }}"
        imagePullPolicy: {{ .pullPolicy }}
        {{- end }}
        name: manager
        ports:
        - containerPort: 9090
          name: http
          protocol: TCP
        - containerPort: 8080
          name: http-prom
          protocol: TCP
        - containerPort: 9440
          name: healthz
          protocol: TCP
        {{- with .Values.sourceController.manager }}
        livenessProbe:
          {{- toYaml .livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .readinessProbe | nindent 10 }}
        resources:
          {{- toYaml .resources | nindent 10 }}
        securityContext:
          {{- toYaml .containerSecurityContext | nindent 10 }}
        volumeMounts:
        - mountPath: /data
          name: data
        - mountPath: /tmp
          name: tmp
      securityContext:
        {{- toYaml .podSecurityContext | nindent 8 }}
      {{- end }}
      volumes:
      - emptyDir: {}
        name: data
      - emptyDir: {}
        name: tmp
