---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm-controller-stack.sourceControllerFullname" . }}-metrics-service
  labels:
    {{- include "helm-controller-stack.sourceControllerLabels" . | nindent 4 }}
spec:
  ports:
    {{- if .Values.kubeRBACProxy.enabled }}
    - name: https-metrics
      port: 8443
      targetPort: https-metrics
      protocol: TCP
    {{- else }}
    - name: http-metrics
      port: 8080
      targetPort: http-metrics
      protocol: TCP
    {{- end }}
  selector:
    {{- include "helm-controller-stack.sourceControllerSelectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "helm-controller-stack.sourceControllerLabels" . | nindent 4 }}
  name: {{ include "helm-controller-stack.sourceControllerFullname" . }}
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: http
  selector:
    {{- include "helm-controller-stack.sourceControllerSelectorLabels" . | nindent 4 }}
