# Default values for empty.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# -- A string to evaluate as a template for rendering kubernetes manifests.
manifests: ""
  #   apiVersion: apps/v1
  #   kind: ConfigMap
  #   metadata:
  #     name: {{ .name }}
  #   data:
  #     something: {{ .something }}
